server {
    # slusa na portu 80
    # 80 je za front, 8080 za back
    listen 80;
    
    # pravila za glavnu putanju, root stranica 
    location / {
        # fizicki direktorijum gdje se nalaze fajlovi
        root /usr/share/nginx/html;
        # index.html je root
        index index.html index.htm;
        # traz folder ili fajl, ako fajl ne postoji, preusmjeri na index.html (za SPA aplikacije)
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}